# Generated by Django 2.2.4 on 2022-01-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220114_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='aderentes',
            field=models.ManyToManyField(related_name='favoritas', to='app.User'),
        ),
    ]
