# Generated by Django 2.2.4 on 2022-01-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_deseo'),
    ]

    operations = [
        migrations.AddField(
            model_name='deseo',
            name='comsumidores',
            field=models.ManyToManyField(related_name='preferencias', to='app.User'),
        ),
    ]
